### ISSUE TITLE
Raise error on regex compilation fail

### ISSUE THREAD

**Issue by nathanrpage97** [kmarius/jsregexp#10]
For both python and javascript the standard behavior is to raise an error when compilation fails. I think it would be good if the default is the same for `jsregexp.compile()`. A separate `jsregexp.compile_safe()` function can be created that prevents error raising. This is a common place practice for other such projects like cjson.

**Comment by kmarius** [comment]
This is also the behavior of the `string` library so we really are the odd one out. 
```lua
> string.match("abc", "[a")
stdin:1: malformed pattern (missing ']')
stack traceback:
        [C]: in function 'match'
        stdin:1: in main chunk
        [C]: ?
```

**Comment by kmarius** [comment]
Cjson actually provides a safe version of the library (used with `require("cjson.safe")`). Is there a general preference of doing it this way instead of having two sets of functions in the same module?

**Comment by nathanrpage97** [comment]
cjson does that since there are a bunch of functions that need protecting for the safe call
