### ISSUE TITLE
Stop hardcodiing CC=gcc

### ISSUE THREAD

**Issue by natthias** [kmarius/jsregexp#24]
Currently, the makefile hardcodes `CC=gcc`, which forces user to invoke `make cc=<c compiler>` to compile the software. 

It would make more sense to just remove the `CC=gcc` and have the Make handle this. For GNU Make, this would just default to cc as the c compiler (cc is usually symlinked to gcc), unless `CC` is set in the environment. 

It would also help distributions such as Chimera Linux, which use llvm/clang for the system toolchain.

**Comment by kmarius** [comment]
I have no objection to removing that option, however I very much don't want try and to make the Makefile work on every environment. Luarocks does a much better job at that.

**Comment by natthias** [comment]
Distros using llvm/clang as the toolchain can't really use luarocks without compiling from source, as they are missing `libgcc`, but that is more of a luarocks issue than anything else. Closing as the issue has been addressed, thank you.
